resources:
  - ../../base/istory-app

namespace: istory-prod

patches:
  - path: patch-lb-annotations.yml
    target:
      kind: Service
      name: istory-app-lb
  - path: patch-deploy.yml
    target:
      kind: Deployment
      name: istory-app-deploy

images:
  # base/istory-app/istory-app-deploy.yml 내의 이미지 이름과 동일해야 변경됨
  - name: bitale/istory
    newTag: latest

configMapGenerator:
  - name: istory-app-config
    behavior: replace
    envs:
      - .env.app.config
    
secretGenerator:
  - name: istory-db-secret
    envs:
      - .env.db.secret
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true